  services:
    server:
      build:
        context: .
        dockerfile: docker/nginx/Dockerfile
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - .:/app/
        - ./certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
        - ./certs/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro
      links:
        - php
      networks:
        - pg-network
    
    db:
      build:
        context: .
        dockerfile: docker/db/Dockerfile
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5433:5432"
      networks:
        - pg-network
      volumes:
        - ./docker/db:/docker-entrypoint-initdb.d
    
    php:
      build:
        context: .
        dockerfile: docker/php/Dockerfile
      volumes:
        - .:/app
      networks:
        - pg-network
      environment:
        PHP_VALUE: |
          session.cookie_secure = 1
          session.cookie_httponly = 1
          session.cookie_samesite = "Lax"
    
    pgadmin-wdpai:
      image: dpage/pgadmin4:latest
      container_name: pg-admin-monsters
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      ports:
        - "5050:80"
      networks:
        - pg-network
    
  networks:
    pg-network:

  volumes:
    pg-data: